# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6qxNHRm6vtGu8eN277jugGZH3H9XMs3
"""

import numpy as np

def ES(losses, confidence=None, VaR=None, use_PnL=False):
    if VaR is None:
        if confidence is None:
            raise ValueError("Either confidence or VaR must be provided.")
        VaR = np.percentile(losses, 100 * (1 - confidence))

    es_value = np.mean(losses[losses < VaR])
    return abs(es_value)