# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEE2gu4YWiMm1tdDVQa7gIVNBZQ82DRt
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r, confidence, principal = 1):
    var_percentile = np.percentile(r, (1 - confidence) * 100)
    out = principal * abs(var_percentile)

    return out