# -*- coding: utf-8 -*-
"""HW_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yx2xoMziz90ka1TWolU3Up3ZBUbb6coi
"""

def WhoAmI():
  return('ys3889')