# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GncS8T6dNLGFhOx1W5tkyblrp9Sbk-v9
"""

import yfinance as yf
import pandas as pd
import numpy as np


def YahooData2returns(YahooData):
  prices = YahooData['Adj Close']
  pricevec=prices.values
  returns=(pricevec[1:]/pricevec[:-1])-1
  return returns

def get_stock_data(symbol):
    data = yf.download(symbol,start=start,end=end)
    return data